### ISSUE TITLE
Create a web presence for your extension (with ease)

### ISSUE THREAD

**Issue by aschrijver** [lgwb89/nudge#35]
This issue is a follow-up to [our discussion](https://community.humanetech.com/t/nudge-v2-addictive-sites-off-by-default-visualise-time-spent-hide-addictive-site-sections/2521/12) on the [Humane Tech](https://humanetech.com) community. From the thread:

> I have no website presence because I have always preferred to spend Nudge dev time working on improvements to the Chrome extension, mostly because I know I’ll end up spending hours and hours endlessly tweaking a landing page once I build one.

There is a very easy way to create a nice-looking website, running at https://nudgeware.io that requires very little effort to set up, and without hosting costs:

- Create a [Github Pages](https://guides.github.com/features/pages/) website on Github running Jekyll, or another static site generator
  - Content is simple markdown stored in `gh-pages` branch in nudge repo, or a separate repo.
  - GH Pages comes with free Letsencrypt SSL certificates with a single click
  - Configure DNS and with a single click you create a CNAME and attach to https://nudgeware.io
  - Select a Jekyll theme that is to your liking
- You'll need is a landing page with Nudge description (features, screenshot, installing) as markdown
  - Add a Privacy Policy. Might use [Termly](https://termly.io/privacy-policy/privacy-policy-generator/) (but read their PP first)
  - Additionally you could have a `blogs` section, publish there first, and then secondarily on Medium
  - Add link to Github repo and ask for Contributions
  - Also add a 'Donate' button to the landing page to get some more funding for further Dev :wink:

> It’s true that you can’t find out who makes Nudge from the Chrome extension page. But I have never tried to keep this a secret - in fact I have written multiple articles on Medium explaining things like exactly what Nudge does, and anyone is welcome to check out my LinkedIn profile.

With the above there is no need to add your name, though you could add a link to your LI profile. With this online presence you are now transparent to people who didn't bump into one of your Medium articles (but e.g. found you on the play store).

**Comment by lgwb89** [comment]
I'm happy to report that over a year after your extremely helpful guide, I've finally created a proper site for Nudge. Thank you @aschrijver!

https://nudgeware.io/
